services:
  caddy:
    image: caddy:2
    ports:
      - "4000:4000"
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: