services:
  caddy:
    image: caddy:2
    ports:
      - "4000:4000"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  calculations-service:
    build:
      context: .
      dockerfile: ./backend/calculations-service/Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=4001
    ports:
      - "4001:4001"

  web:
    build:
      context: .
      dockerfile: ./frontend/web/Dockerfile
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:4000/api/
      - PORT=3000
    ports:
      - "3000:3000"

volumes:
  caddy_data:
  caddy_config: